car_brands = [
    "Abarth",
    "Porsche",
    "Ferrari",
    "Maserati",
    "Mercedes",
    "Bugatti",
    "Aston Martin",
    "Renault",
    "Toyoya",
    "Honda",
    "Peugeot",
    "Pagani",
    "Fiat",
    "Audi",
    "Land Rover",
    "Bentley",
    "McLaren",
    "Lexus",
    "Nissa",
    "Tesla",
    "Alpine",
    "Caterham",
    "Chrysler",
    "Jaguar",
    "Maybach",
    "Mitsubishi",
    "Vauxhall",
    "Polestar",
    "volvo",
    "Ascari",
    "Gumpert",
    "General Motors",
    "Alfa Romeo",

]