country_list [
    "Pakistan",
    "Iran",
    "France",
    "Wales",
    "Italy",
    "Argentina",
    "Lithuania",
    "Greenland",
    "Iceland",
    "Moldova",
    "Paraguay",
    "Uruguay",
    "Portugal",
    "Albania",
    "Croatia",
    "Bangladesh",
    "Dominican Republic",
    "Haiti",
    "Indonesia",
    "Azerbaijan",
    "Norway",
    "Sweden",
    "Finland",
    "Russia",
    "Mongolia",
    "Australia",
    "Sierra Leone",
    "Seychelles",
    "Montenegro",
    "Suriname",
    "Thailand",
    "Cambodia",
    "Bostwana",
]